[server]
headless = true

[browser]
serverAddress = "localhost"

[theme]
primaryColor = "#4B0082"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#000000"
font = "sans serif"

[server]
scriptName = "app.py"  # or "streamlit_app.py"
