[server]
headless = true
scriptName = "app.py" # Move this line under the first [server] block

[browser]
serverAddress = "localhost" # Consider removing this for cloud deployments


[theme]
primaryColor = "#4B0082"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#000000"
font = "sans serif"